version: "3"

vars:
  GREETING: Hello, AI Commit!

tasks:
  default:
    cmd: task --list-all
  build:
    cmds:
      - cargo build -r
      - cp /Users/john/.cargo/target/release/ai-commit /opt/bin/ai-commit
  commit:
    cmds:
      - git add .
      - ai-commit
